server:
  port: 8040

spring:
  datasource:
    url: jdbc:mysql://fcfs-event-db:3306/kakao_gift?autoReconnect=true
    username: root
    password: root
  h2:
    console:
      enabled: true
  data:
    redis:
      host: fcfs-redis
      port: 6379
      password: password
